config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  get    '/logout', to: 'sessions#destroy'
  get    '/search', to: 'search#search'
  get    '/change_tab', to: 'static_pages#change_tab'

  resources :users, param: :user_id do
    member do
      get 'follow'
    end
  end

  resources :items, param: :item_id do
    member do
      get 'like'
      get 'toggle_mode'
      get 'change_type'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  self.primary_key = :id_name
  has_many :following_relationships, class_name: "Relationship", dependent: :destroy, foreign_key: "follower_id"
  has_many :following_users, through: :following_relationships, source: 'following'
  has_many :follower_relationships, class_name: "Relationship", dependent: :destroy, foreign_key: "following_id"
  has_many :followers, through: :follower_relationships
  has_many :follow_tag_relationships, dependent: :destroy
  has_many :following_tags, through: :follow_tag_relationships, source: :tag

  has_many :like_relationships, dependent: :destroy
  has_many :like_items, through: :like_relationships, source: :item

  has_many :items, dependent: :destroy, primary_key: "id_name"
  attr_accessor :remember_token
  
  has_secure_password

  email_regex = /\A[a-zA-Z0-9_\#!$%&`'*+\-{|}~^\/=?\.]+@[a-zA-Z0-9][a-zA-Z0-9\.-]+\z/
  validates :id_name,     presence: true,
                        uniqueness: true,
                            length: (1..50)

  validates :screen_name, presence: true,
                            length: (1..50)

  validates :email,       presence: true,
                        uniqueness: true,
                            length: { maximum: 50 },
                            format: { with: email_regex }


  def like?(item)
    like_relationships.exists?(item_id: item.id)
  end

  def like!(item)
    like_relationships.create!(item: item) unless self.like?(item)
  end
  
  def unlike!(item)
    like_relationships.find_by(item_id: item.id).destroy
  end

  def add_follower(user)
    follower_relationships.create!(follower_id: user.id)
  end

  def followed?(user)
    follower_relationships.exists?(follower_id: user.id)
  end

  def remove_follower(user)
    follower_relationships.find_by(follower_id: user.id).destroy
  end

  def following?(other)
    other.followed?(self)
  end

  def follow!(other)
    other.add_follower(self)
  end

  def unfollow!(other)
    other.remove_follower(self)
  end

  def remember
    @remember_token = User.generate_token
    update_attribute(:remember_digest, User.digest(@remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def timeline
    Item.where(id: self.following_users.map{|user| user.items.map(&:id)}).order(created_at: :desc).limit(10)
  end

  class << self
    def generate_token
      SecureRandom.urlsafe_base64
    end

    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :update,  :destroy]
  before_action :user_exists?,  only: [:show, :edit ]
  helper_method :user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @items = user.items.paginate(page: params[:page], per_page: 5)
  end

  def index
  end

  def edit
  end

  def update
    if user.update_attributes(user_params)
      flash[:success] = "User updated" 
      redirect_to user
    else
      flash[:danger] = "Failed to update"
      render 'edit'
    end
  end

  def destroy
    if user.destroy
      flash[:success] = "Your account deleted"
    else
      flash[:danger] = "Failed to delete account"
    end
    redirect_to root_url
  end


  def follow
    if current_user.following?(user)
      current_user.unfollow!(user)
      @message = "Follow".to_json
    else
      current_user.follow!(user)
      @message = "Unfollow".to_json
    end
  end

  def user
    if defined? @user
      return @user
    else
      puts "SQL"
      @user = User.find_by(id_name: params[:user_id])
    end
  end

  def user_exists?
    unless user
      flash[:danger] = "User not found"
      redirect_to root_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:id_name, :screen_name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>user setting</h1>
<%= render "layouts/error_messages", model: user %>

<%= form_for user do |f| %>
  <%= f.label :id_name, "ID" %>
  <%= f.text_field :id_name, placeholder: "Enter new ID", class: "form-control body-input" %>

  <%= f.label :screen_name, "Screen name" %>
  <%= f.text_field :screen_name, placeholder: "Enter new Screen name", class: "form-control body-input" %>

  <%= f.label :email, "Email" %>
  <%= f.email_field :email, placeholder: "Enter Eail address", class: "form-control body-input" %>

  <%= f.label :password, "Password" %>
  <%= f.password_field :password, placeholder: "Enter Password", class: "form-control body-input" %>

  <%= f.label :password_confirmation, "Password confirmation" %>
  <%= f.password_field :password_confirmation, placeholder: "Enter Password again", class: "form-control body-input" %>


  <%= f.submit "Update", class: "btn btn-outline-primary" %>
<% end %>

<%= link_to "Delete user", user_path(@user.id_name), method: :delete, class: "btn btn-outline-danger" %>

app/views/users/follow.js.erb
$('#follow-or-unfollow').html(<%= raw @message %>);

app/views/users/index.html.erb
<h1>index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/items.html.erb
<% provide :title, "Items" %>
<%= render 'layouts/items' %>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<%= render "layouts/error_messages", model: @user %>
<h1 class="text-center">Welcome to ASK!</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :id_name, "ID" %>
  <%= f.text_field :id_name, placeholder: "Enter ID", class: "form-control body-input" %>

  <%= f.label :screen_name, "Screen name" %>
  <%= f.text_field :screen_name, placeholder: "Enter Screen name", class: "form-control body-input" %>

  <%= f.label :email, "Email" %>
  <%= f.email_field :email, placeholder: "Enter Email address", class: "form-control body-input" %>

  <%= f.label :password, "Password" %>
  <%= f.password_field :password, placeholder: "Enter Password", class: "form-control body-input" %>

  <%= f.label :password_confirmation, "Password confirmation" %>
  <%= f.password_field :password_confirmation, placeholder: "Enter Password again", class: "form-control body-input" %>


  <%= f.submit "Sign up", class: "btn btn-outline-primary" %>
<% end %>

app/views/users/show.html.erb
<h1 class="title"><%= user.screen_name %></h1>
<p>
Follow: <%= user.following_users.length %>
<br>
Follower: <%= user.followers.length %>
</p>
<% if current_user != user %>
  <%= link_to (current_user.following?(@user) ? "Unfollow": "Follow"), follow_user_path, id: "follow-or-unfollow", class: "submit-button", remote: true %>
<% else %>
  <div class="user-menu">
    <%= link_to "Setting", edit_user_path, class: "btn btn-outline-dark" %>
  </div>
<% end %>
<% @items.each do |item| %>
  <%= link_to item_path(item), class: "item-headline-link" do %>
    <div class="item-headline">
      <h5><%= item.title %></h5>
      <p><%= "by " + item.user.id_name %></p>
      <hr>
    </div>
  <% end %>
<% end %>
<%= will_paginate @items, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>