config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  get    '/logout', to: 'sessions#destroy'
  get    '/search', to: 'search#search'
  get    '/change_tab', to: 'static_pages#change_tab'

  resources :users, param: :user_id do
    member do
      get 'follow'
    end
  end

  resources :items, param: :item_id do
    member do
      get 'like'
      get 'toggle_mode'
      get 'change_type'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, foreign_key: "user_id", foreign_type: "string"
  has_many :item_tag_relationships, dependent: :destroy
  has_many :tags, through: :item_tag_relationships, source: :tag
  has_many :like_relationships, dependent: :destroy
  has_many :liked_users, through: :like_relationships, source: :user
  validates :title, presence: true, length: (1..100)
  validates :content, presence: true, length: (15..30000)

  def liked?(user)
    like_relationships.exists?(user_id: user.id)
  end

  def add(tag)
    item_tag_relationships.create!(tag_id: tag.id)
  end

  def remove(tag)
    item_tag_relationships.find_by(tag_id: tag.id).destroy
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ApplicationHelper
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  before_action :item_exists?,   only: [:show, :edit ]
  helper_method :item

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.build(item_params)
    toggle_mode do
      if @item.save
        flash[:success] = "Item posted"
        redirect_to root_url
      else
        render 'new'
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    toggle_mode do
      if item.update_attributes(item_params)
        flash[:success] = "Item updated"
        redirect_to item_path(@item)
      else
        flash[:danger] = "Failed to update"
        render 'edit'
      end
    end
  end

  def destroy
    if item.destroy
      flash[:success] = "Item deleted"
    else
      danger[:danger] = "Failed to delete item"
    end
    redirect_to root_url
  end

  def like
    p params[:test]
    if current_user.like?(item)
      current_user.unlike!(item)
      @src = "https://img.icons8.com/material-outlined/24/000000/hearts.png".to_json
    else
      current_user.like!(item)
      @src = "https://img.icons8.com/material/24/000000/hearts.png".to_json
    end
  end

  def toggle_mode
    @title   = params[:item][:title]
    @content = params[:item][:content]
    @slidable_check = params[:item][:slidable]
    case params[:commit]
    when "Submit"
      yield
    when "Edit"
      @visible = "#editmode"
      @hidden = "#previewmode"
      render "toggle_mode"
    when "Preview"
      @visible = "#previewmode"
      @hidden = "#editmode"
      render "toggle_mode"
      p md2html(@content)
    end
  end

  def change_type
  end

  def item
    return @item if defined? @item
    @item = Item.find_by(id: params[:item_id])
  end

  def item_exists?
    unless item
      flash[:danger] = "Item not found"
      redirect_to root_url
    end
  end


  private

  def item_params
    params.require(:item).permit(:title, :content, :slidable)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item_editor.html.erb
<%= render "layouts/error_messages", model: item %>
<%= form_for item, remote: true do |f| %>
  <%= f.check_box :slidable, id: "slidable-check" %>
  <%= f.submit "Edit", remote: true %>
  <%= f.submit "Preview", remote: true %>

  <div id="editmode">
    <%= f.text_field :title, placeholder: "input Title", class: "title-input" %>
    <%= f.text_area :content, class: "item-input" %>
  </div>
  <div id="previewmode">
    <div id="item-preview" class="item-preview"></div>
    <div id="slide-preview" class="slide-preview"></div>
  </div>
  <%= f.submit "Submit", class: "submit-button" %>
<% end %>
<script>
  $("#previewmode").hide();
</script>

app/views/items/_slidable_item.html.erb
<h1><%= title %></h1>
<hr>
<div id="slide-screen" class="slide-screen"></div>
<ul class="slide-bar" id="slide-bar">
  <% md2html(content).gsub("<hr />", "<hr>").split("<hr>").each do |page| %>
    <li class="slide-page" id="slide-page" tabindex="-1">
      <div>
        <%= page.html_safe %>
      </div>
    </li>
  <% end %>
</ul>

<script>
  $("#slide-bar li").click(function(event){
    $("#slide-bar li").css("border", "none");
    $(this).css("border", "10px solid limegreen");
    $("#slide-screen").html($(this).html());
  });

  $("#slide-bar li").keydown(function(event){
    console.log(event.keyCode);
    if(event.keyCode == 39){
      $(this).next().click();
      $(this).next().focus();
    }else if(event.keyCode == 37){
      $(this).prev().click();
      $(this).prev().focus();
    }else if(event.keyCode == 37){
    }
  });

  $("#slide-bar li").first().click();
  $("#slide-bar li").first().focus();
</script>

app/views/items/edit.html.erb
<% provide(:title, item.title) %>
<%= render "items/item_editor" %>

app/views/items/like.js.erb
$('#like-or-unlike').html('<img src=<%= raw @src %>>');

app/views/items/new.html.erb
<% provide(:title, "Create new item") %>
<%= render "items/item_editor" %>

app/views/items/show.html.erb
<h1 class="item-title"><%= item.title %></h1>
<%= link_to("Edit", edit_item_path(item), class: "btn btn-outline-dark") if item.user == current_user %>
<br>
<%= item.user.screen_name %>
<p><img src="https://img.icons8.com/material-outlined/15/000000/hearts.png"> <%= item.liked_users.length %></p>
<hr>
<% if item.slidable %>
  <%= render "slidable_item", title: item.title, content: item.content %>
<% else %>
  <%= raw md2html item.content %><br>
<% end %>
<hr>
<br>
<% if logged_in? %>
  <%= link_to like_item_path, id: "like-or-unlike", remote: true do %>
    <% if current_user.like?(item) %>
      <img src="https://img.icons8.com/material/24/000000/hearts.png">
    <% else %>
      <img src="https://img.icons8.com/material-outlined/24/000000/hearts.png">
    <% end %>
  <% end %>
<% end %>

app/views/items/toggle_mode.js.erb
var visible = "<%= @visible %>"
var hidden  = "<%= @hidden %>"
var slidable_check = "<%= @slidable_check %>"

console.log(slidable_check);

$(visible).show();
$(hidden).hide();

if(visible == "#previewmode"){
  $("#item-preview").html("");
  if(slidable_check == "0"){
    $("#slide-preview").hide();
    $("#item-preview").show();
    $("#item-preview").html("<h1>" + <%= raw md2html(@title).to_json %> + "</h1><hr>" + <%= raw md2html(@content).to_json %>);
  }else{
    $("#item-preview").hide();
    $("#slide-preview").show();
    $("#slide-preview").html(<%= raw render("slidable_item", title: @title, content: @content).to_json %>);
    console.log($("#slide-preview").html());
  }
}

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>