config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  get    '/logout', to: 'sessions#destroy'
  get    '/search', to: 'search#search'
  get    '/change_tab', to: 'static_pages#change_tab'

  resources :users, param: :user_id do
    member do
      get 'follow'
    end
  end

  resources :items, param: :item_id do
    member do
      get 'like'
      get 'toggle_mode'
      get 'change_type'
    end
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<ul class="topnav">
  <li class="left"><%= link_to "ASK", root_url %></li>
  <% if logged_in? %>
    <li class="left"><%= link_to "MyPage", current_user %></li>
    <li class="right"><%= link_to "LogOut", logout_path %></li>
    <li class="right"><%= link_to "Setting", edit_user_path(current_user) %></li>
    <li class="right"><%= link_to "NewItem", new_item_path %></li>

  <% else %>
    <li class="right"><%= link_to "LogIn", login_path %></li>
  <% end %>
  <%= form_with url: "/search", method: "get", local: true, class: "search" do |f| %>
    <%= f.text_field :q, class: "search-form", value: params[:q], autocomplete: 'off', spellcheck: false, placeholder: "search"  %>
    <%= f.submit :search, class: "search-btn" %>
  <% end %>
</ul>

app/views/layouts/_header_.html.erb
<nav class="navbar navbar-expand-md navbar-dark" style="background-color: #4c8dcb">
  <%= link_to "ASK", root_url, class: "navbar-brand" %>

  <ul class="navbar-nav">
    <%= link_to "Home", "#", class: "nav-link" %>
    <%= link_to "Index", "#", class: "nav-link" %>
  </ul>

  <ul class="navbar-nav ml-auto">
    <%= form_with url: "/search", local: true, method: "get" do |f| %>
      <%= f.text_field :q, class: "inline-form" %>
      <%= f.submit "Search", class: "btn", style: "color: white;background-color: #417ab1" %>
    <% end %>
    <% unless logged_in? %>
      <%= link_to signup_path, class: "btn btn-warning nav-link", style: "color: black;" do %>
        <img src="https://img.icons8.com/metro/26/000000/gender-neutral-user.png">Sign up
      <% end %>
      <%= link_to login_path, class: "btn btn-warning nav-link", style: "color: black;" do %>
        <img src="https://img.icons8.com/ios-glyphs/26/000000/enter-2.png">Log in
      <% end %>
    <% end %>
  </ul>
</nav>

app/views/layouts/_items.html.erb
<div>
  <% @items.each do |item| %>
    <%= link_to item.title, item_path(item) %>
    <br>
    <%= item.user.screen_name %>
    <br>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= yield(:title) %>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/top.html.erb
<div class="top-headline-box">
  <h1>Welcome!</h1>
  <%= link_to "Sign up", signup_path, class: "button center" %>
</div>